export default [
    {
      id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
        question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
        answer: '축구하다가',
        result: "correct",
        category: "Reading",
        level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
        question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
        answer: '축구하다가',
        result: "correct",
        category: "Reading",
        level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },
    {
        id: 1,
      question: "운동장에서 (          ) 친구와 부딫혀서 넘어졌다.",
      answer: '축구하다가',
      result: "correct",
      category: "Reading",
      level: "2",
    },

  ];
  